SEP = ";"

ERROR = "ERR"
SUCCESS = "SUC"

ACK = "ACK"

MATCH_MAKER_PORT = 8080
SERVER_ADDRESS = "127.0.0.1"

MATCH_MAKER_CREATE_ROOM = "MCR"
MATCH_MAKER_JOIN_ROOM = "MJR"

MATCH_MAKER_GAME_START = "MGS"

USER_EVENTS_LIST_MSG = "CEL"
SERVER_EVENT_LIST_MSG = "SEL"

TARGET_FRAME_TIME = 1 / 60  # 60 FPS
