SEP = ";"

ERROR = "ERR"
SUCCESS = "SUC"

ACK = "ACK"

MATCH_MAKER_PORT = 8080
SERVER_ADDRESS = "127.0.0.1"

MATCH_MAKER_CREATE_ROOM = "MCR"
MATCH_MAKER_JOIN_ROOM = "MJR"

MATCH_MAKER_GAME_START = "MGS"

EVENTS_LIST_MSG = "ELM" 